### ISSUE TITLE
GLIBC_2.35 not found 

### ISSUE THREAD

**Issue by bthj** [ircam-ismm/node-web-audio-api#22]
Hi

With the latest version (0.10.0) I'm getting the error:
```
`GLIBC_2.35' not found (required by ... node_modules/node-web-audio-api/node-web-audio-api.linux-x64-gnu.node)
```

I've tried building and installing `glibc` to a separate directory, like so:
```
mkdir glibc-install
glibc-install/
wget http://ftp.gnu.org/gnu/glibc/glibc-2.35.tar.gz
tar -zxvf glibc-2.35.tar.gz
cd glibc-2.35
mkdir build
cd build/
../configure --prefix=/custom/dir/glibc-2.35
make
make install
```
setting `LD_LIBRARY_PATH` to `lib` in that directory: 
```
export LD_LIBRARY_PATH=/custom/dir/glibc-2.35/lib:$LD_LIBRARY_PATH
```
but that results in segmentation fault.

The machine I observe this on (almalinux), does in fact have an earlier version:
```
$ ldd --version
ldd (GNU libc) 2.28
```
- but reverting to node-web-audio-api v0.7.0 solves the issue.

Is there maybe an easy backwards compatibility fix for the current release?

**Comment by b-ma** [comment]
Hey Björn,

Damn, I'm not very skilled with this kind of stuff unfortunately, so I'm really not sure how I can help. 

However, I updated the version of the docker image I use to build the x64 image last time (https://github.com/ircam-ismm/node-web-audio-api/commit/5f73163e8b3469dfb3252eddb397af63e152af3b), maybe that could the issue?
After some googling I came across this [link](https://pyinstaller.org/en/stable/usage.html#making-gnu-linux-apps-forward-compatible) which state that _"The solution is to always build your app on the oldest version of GNU/Linux you mean to support. It should continue to work with the libc found on newer versions."_

Could you have a try building the binary through the docker image, just reverting `FROM node:18` to `FROM node:14`? If it works I could just revert that change on my side and redo a release

**Comment by bthj** [comment]
Neither am I skilled in navigating this dependency hell : )

But building though a docker image, created `FROM:14`, made the difference in this case (on a machine with GNU libc 2.28).

---

For the record, this is what I did:
- made sure the Rust toolchain was installed:
```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

- built the  image, from within `deploy/docker_x86_64-unknown-linux-gnu/`, with:
```
sudo docker build -t bbmmaa/build-x86_64 .
```
- generated the sources (from the project root):
```
npm i
npm run generate
```

- and then built the binary with:
```
node deploy/build-linux-gnu-docker.mjs
```

**Comment by b-ma** [comment]
Hey,

Thanks for the feedback, seems like a good news, I will revert this then and make a new release as soon as possible then

**Comment by b-ma** [comment]
Hey Börn, 

I just released v0.11.0, it should be fixed, could you confirm it is ok on your side?

Note that the `decodeAudioData` signature has changed (it now compliant with the spec cf. https://github.com/ircam-ismm/node-web-audio-api/pull/25) and that the load helper has been removed, this may have an impact on your project. All examples have been updated accordingly.

**Comment by bthj** [comment]
Thanks Benjamin, I'm unable to reproduce the error with this version 🎉

**Comment by b-ma** [comment]
Cool, perfect!

**Comment by ScreamZ** [comment]
@b-ma @bthj I'm still experiencing this issue 

`Error: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /root/screamz/node_modules/.pnpm/node-web-audio-api@0.15.0/node_modules/node-web-audio-api/node-web-audio-api.linux-arm64-gnu.node)`

I'm running on debian on orangepi

**Comment by pglootz** [comment]
I'm also experiencing the same problem if you have any suggestions on how to fix?

> /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /home/web-audio-api-demo/node_modules/node-web-audio-api/node-web-audio-api.linux-arm64-gnu.node)

With Debian GNU/Linux 11 (bullseye) on Raspberry Pi
Node.js v21.6.1

**Comment by b-ma** [comment]
Thanks for the feedback, this is quite annoying indeed

Unfortunately, as I don't really have any clean solution to fix that for now (added an item in #55), the only suggestion I can make is to build the lib from source: https://github.com/ircam-ismm/node-web-audio-api?tab=readme-ov-file#manual-build, it should just build against the GLIBC version of your system and it should be ok.

Could you let me know which GLIBC version is installed on your system? (`ldd --version`)

**Comment by pglootz** [comment]
Thank you for adding it as an item. GLIB version installed on the system is 2.31
> ldd (Debian GLIBC 2.31-13+rpt2+rpi1+deb11u7) 2.31

**Comment by idootop** [comment]
PS: If you encounter the following error during build:
```shell
The system library `alsa` required by crate `alsa-sys` was not found.
```
You need to install dependencies that include alsa, such as `libasound2-dev`.
```shel
sudo apt install libasound2-dev
```

**Comment by b-ma** [comment]
Thank, I added a note in the README on this point
